package com.aitesting.healthcare.api;

import com.aitesting.api.models.FhirModels.*;
import com.aitesting.shared.dataprovider.TestDataFactory;

import java.time.LocalDate;
import java.util.List;

/**
 * FhirTestDataFactory — FHIR R4 synthetic test data factory.
 *
 * ═══════════════════════════════════════════════════════════════════════
 * DESIGN: CRTP Subclass of TestDataFactory
 * ═══════════════════════════════════════════════════════════════════════
 *
 * Extends TestDataFactory<FhirTestDataFactory> — inherits all generic
 * methods (withRandomId, nonExistentId, etc.) automatically.
 * New generic methods added to TestDataFactory propagate here for free.
 *
 * ═══════════════════════════════════════════════════════════════════════
 * HIPAA COMPLIANCE
 * ═══════════════════════════════════════════════════════════════════════
 *
 * ALL patient data is synthetic — never real PHI (Protected Health Info).
 * HIPAA violations carry fines of $100 to $50,000 per violation.
 *
 * Safety rules applied:
 *   → Patient IDs prefixed with "TEST-" — clearly identifies test data
 *   → Names generated by Java Faker — realistic but fake
 *   → DOBs are calculated ages — not real birth dates
 *   → No real SSNs, no real MRNs, no real provider NPIs
 *
 * ═══════════════════════════════════════════════════════════════════════
 * USAGE
 * ═══════════════════════════════════════════════════════════════════════
 *
 *   // Builder style:
 *   Patient p = FhirTestDataFactory.create()
 *       .withRandomId()
 *       .withAge(35)
 *       .withGender("male")
 *       .buildPatient();
 *
 *   // Static convenience:
 *   Patient adult    = FhirTestDataFactory.adultPatient();
 *   Patient pediatric = FhirTestDataFactory.pediatricPatient();
 *   Patient senior   = FhirTestDataFactory.seniorPatient();
 */
public final class FhirTestDataFactory
        extends TestDataFactory<FhirTestDataFactory> {

    // ── FHIR coding system URLs ───────────────────────────────────────────────

    public static final String ICD10_SYSTEM =
        "http://hl7.org/fhir/sid/icd-10-cm";
    public static final String CPT_SYSTEM =
        "http://www.ama-assn.org/go/cpt";
    public static final String NPI_SYSTEM =
        "http://hl7.org/fhir/sid/us-npi";
    public static final String MRN_SYSTEM =
        "http://hospital.example.org/mrn";
    public static final String SNOMED_SYSTEM =
        "http://snomed.info/sct";

    // ── Common test codes ─────────────────────────────────────────────────────

    // ICD-10 diagnosis codes
    public static final String ICD10_PNEUMONIA     = "J18.9";
    public static final String ICD10_HYPERTENSION  = "I10";
    public static final String ICD10_DIABETES      = "E11.9";
    public static final String ICD10_CHEST_PAIN    = "R07.9";
    public static final String ICD10_ANNUAL_EXAM   = "Z00.00";

    // CPT procedure codes
    public static final String CPT_OFFICE_VISIT    = "99213";
    public static final String CPT_ANNUAL_EXAM     = "99395";
    public static final String CPT_CHEST_XRAY      = "71046";
    public static final String CPT_MRI_BRAIN       = "70553";
    public static final String CPT_BLOOD_PANEL     = "80053";

    // ── Builder state ─────────────────────────────────────────────────────────

    private int    age    = 35;
    private String gender = "unknown";
    private String icd10  = ICD10_ANNUAL_EXAM;
    private String cpt    = CPT_OFFICE_VISIT;

    // ── Entry point ───────────────────────────────────────────────────────────

    public static FhirTestDataFactory create() {
        return new FhirTestDataFactory().withRandomId();
    }

    private FhirTestDataFactory() {}

    // ── Builder methods ───────────────────────────────────────────────────────

    public FhirTestDataFactory withAge(int age) {
        this.age = age;
        return this;
    }

    public FhirTestDataFactory withGender(String gender) {
        this.gender = gender;
        return this;
    }

    public FhirTestDataFactory withDiagnosis(String icd10Code) {
        this.icd10 = icd10Code;
        return this;
    }

    public FhirTestDataFactory withProcedure(String cptCode) {
        this.cpt = cptCode;
        return this;
    }

    // ── Build methods ─────────────────────────────────────────────────────────

    @Override
    public java.util.Map<String, Object> build() {
        return java.util.Map.of(
            "resourceType", "Patient",
            "id", "TEST-" + this.id
        );
    }

    /** Build a Patient FHIR resource. */
    public Patient buildPatient() {
        String firstName = faker.name().firstName();
        String lastName  = faker.name().lastName();
        String patientId = "TEST-" + String.format("%08d", this.id);

        return Patient.builder()
            .id(patientId)
            .resourceType("Patient")
            .name(List.of(Patient.Name.builder()
                .use("official")
                .family(lastName)
                .given(List.of(firstName))
                .build()))
            .birthDate(LocalDate.now().minusYears(age).toString())
            .gender(gender.isEmpty() ? randomGender() : gender)
            .identifier(List.of(Patient.Identifier.builder()
                .system(MRN_SYSTEM)
                .value(patientId)
                .build()))
            .address(List.of(Patient.Address.builder()
                .city(faker.address().city())
                .state(faker.address().stateAbbr())
                .postalCode(faker.address().zipCode())
                .country("US")
                .build()))
            .telecom(List.of(Patient.Telecom.builder()
                .system("phone")
                .value(faker.phoneNumber().phoneNumber())
                .use("home")
                .build()))
            .build();
    }

    /** Build an Encounter FHIR resource. */
    public Encounter buildEncounter(String patientId) {
        return Encounter.builder()
            .id("TEST-ENC-" + String.format("%08d", this.id))
            .resourceType("Encounter")
            .status("finished")
            .classCode(Encounter.EncounterClass.builder()
                .system("http://terminology.hl7.org/CodeSystem/v3-ActCode")
                .code("AMB")
                .display("ambulatory")
                .build())
            .subject(Reference.builder()
                .reference("Patient/" + patientId)
                .build())
            .period(Period.builder()
                .start(LocalDate.now().minusDays(1) + "T09:00:00Z")
                .end(LocalDate.now().minusDays(1) + "T10:00:00Z")
                .build())
            .diagnosis(List.of(Encounter.Diagnosis.builder()
                .condition(Reference.builder()
                    .reference("Condition/TEST-COND-001")
                    .build())
                .rank(1)
                .build()))
            .build();
    }

    /** Build a Claim FHIR resource. */
    public Claim buildClaim(String patientId) {
        return Claim.builder()
            .id("TEST-CLM-" + String.format("%08d", this.id))
            .resourceType("Claim")
            .status("active")
            .type(CodeableConcept.builder()
                .coding(List.of(Coding.builder()
                    .system("http://terminology.hl7.org/CodeSystem/claim-type")
                    .code("professional")
                    .display("Professional")
                    .build()))
                .build())
            .use("claim")
            .patient(Reference.builder()
                .reference("Patient/" + patientId)
                .build())
            .provider(Reference.builder()
                .reference("Practitioner/TEST-NPI-1234567890")
                .build())
            .insurer(Reference.builder()
                .reference("Organization/TEST-INSURER-001")
                .build())
            .diagnosis(List.of(Claim.Diagnosis.builder()
                .sequence(1)
                .diagnosisCodeableConcept(CodeableConcept.builder()
                    .coding(List.of(Coding.builder()
                        .system(ICD10_SYSTEM)
                        .code(icd10)
                        .build()))
                    .build())
                .build()))
            .item(List.of(Claim.Item.builder()
                .sequence(1)
                .productOrService(CodeableConcept.builder()
                    .coding(List.of(Coding.builder()
                        .system(CPT_SYSTEM)
                        .code(cpt)
                        .display("Office visit")
                        .build()))
                    .build())
                .unitPrice(Money.builder().value(150.00).currency("USD").build())
                .quantity(1.0)
                .build()))
            .total(Money.builder().value(150.00).currency("USD").build())
            .build();
    }

    /** Build a Prior Authorization request. */
    public PriorAuth buildPriorAuth(String patientId) {
        return PriorAuth.builder()
            .id("TEST-PA-" + String.format("%08d", this.id))
            .resourceType("Claim")
            .status("active")
            .use("preauthorization")
            .patient(Reference.builder()
                .reference("Patient/" + patientId)
                .build())
            .provider(Reference.builder()
                .reference("Practitioner/TEST-NPI-1234567890")
                .build())
            .insurer(Reference.builder()
                .reference("Organization/TEST-INSURER-001")
                .build())
            .item(List.of(PriorAuth.Item.builder()
                .sequence(1)
                .productOrService(CodeableConcept.builder()
                    .coding(List.of(Coding.builder()
                        .system(CPT_SYSTEM)
                        .code(cpt)
                        .display("Requested procedure")
                        .build()))
                    .build())
                .quantity(1)
                .build()))
            .created(java.time.Instant.now().toString())
            .outcome("queued")
            .build();
    }

    // ── Static convenience methods ────────────────────────────────────────────

    /** Standard adult patient (age 35). */
    public static Patient adultPatient() {
        return create().withAge(35).withGender("female").buildPatient();
    }

    /** Pediatric patient (age 8). */
    public static Patient pediatricPatient() {
        return create().withAge(8).withGender("male").buildPatient();
    }

    /** Senior patient (age 72) — Medicare eligible. */
    public static Patient seniorPatient() {
        return create().withAge(72).withGender("female").buildPatient();
    }

    /** Newborn patient (age 0). */
    public static Patient newbornPatient() {
        return create().withAge(0).withGender("male").buildPatient();
    }

    /** Patient with missing required gender field — for 400 tests. */
    public static Patient patientMissingGender() {
        Patient p = adultPatient();
        p.setGender(null);
        return p;
    }

    /** Standard ambulatory encounter. */
    public static Encounter ambulatoryEncounter(String patientId) {
        return create().buildEncounter(patientId);
    }

    /** Standard professional claim. */
    public static Claim professionalClaim(String patientId) {
        return create()
            .withDiagnosis(ICD10_PNEUMONIA)
            .withProcedure(CPT_OFFICE_VISIT)
            .buildClaim(patientId);
    }

    /** Prior auth for elective MRI — complex procedure needing approval. */
    public static PriorAuth electiveMriPriorAuth(String patientId) {
        return create()
            .withProcedure(CPT_MRI_BRAIN)
            .buildPriorAuth(patientId);
    }

    /** Prior auth for routine office visit — usually auto-approved. */
    public static PriorAuth routineVisitPriorAuth(String patientId) {
        return create()
            .withProcedure(CPT_OFFICE_VISIT)
            .buildPriorAuth(patientId);
    }

    // ── Helper ────────────────────────────────────────────────────────────────

    private String randomGender() {
        String[] genders = {"male", "female", "other", "unknown"};
        return genders[random.nextInt(genders.length)];
    }
}
